fixtures:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref:  "4.1.0"
    firewall:
      repo: "puppetlabs/firewall"
      ref:  "1.7.0"
    sudo:
      repo: "abstractit/sudo"
      ref:  "1.2.0"
    concat:
      repo: "puppetlabs/concat"
      ref:  "1.2.0"
    monitoring:
      repo: "abstractit/monitoring"
      ref:  "1.3.6"
  symlinks:
    nrpe: "#{source_dir}"
